//
//  BonjourDiscoveryTypes.swift
//  SideStore
//
//  Created by Magesh K on 4/7/26.
//  Copyright © 2026 SideStore. All rights reserved.
//

import Foundation

public let commonServiceTypesToBrowse: [String] = [
    "_altserver._tcp.",
    "_remotepairing-pairable-host._tcp.",
    "_remotepairing-manual-pairing._tcp.",
    "_airplay._tcp.",
    "_raop._tcp.",
    "_sftp-ssh._tcp.",
    "_sleep-proxy._udp.",
    "_ssh._tcp.",
    "_apple-mobdev2._tcp.",
    "_asquic._udp.",
    "_companion-link._tcp.",
    "_meshcop._udp.",
    "_remotepairing._tcp.",
    "_rp-tunnel._tcp.",
    "_srpl-tls._tcp.",
    "_trel._udp.",
    "_http._tcp.",
    "_https._tcp.",
    "_smb._tcp.",
    "_afpovertcp._tcp.",
    "_printer._tcp.",
    "_ipp._tcp.",
    "_ipps._tcp.",
    "_scanner._tcp.",
    "_daap._tcp.",
    "_dpap._tcp.",
    "_airport._tcp.",
    "_homekit._tcp.",
    "_hap._tcp.",
    "_touch-able._tcp.",
    "_spotify-connect._tcp.",
    "_googlecast._tcp.",
    "_device-info._tcp.",
    "_workstation._tcp.",
    "_rfb._tcp.",
    "_net-assistant._udp.",
    "_rdlink._tcp.",
    "_stikpairprobe._tcp.",
    "_webdav._tcp.",
    "_webdavs._tcp.",
    "_ftp._tcp.",
    "_telnet._tcp.",
    "_coap._udp.",
    "_coaps._udp.",
    "_mqtt._tcp.",
    "_adb._tcp.",
    "_airdrop._tcp.",
    "_sidecar._tcp.",
    "_sonos._tcp.",
    "_plex._tcp.",
    "_amzn-alexa._tcp.",
    "_home-assistant._tcp.",
    "_rtsp._tcp.",
    "_sip._udp.",
    "_sip._tcp.",
    "_h323._tcp.",
    "_h323._udp.",
    "_ws._tcp.",
    "_wss._tcp.",
    "_remoted._tcp.",
    "_coredevice._tcp.",
    "_appletv-v2._tcp.",
    "_apple-mobdev._tcp.",
    "_jitstreamer._tcp.",
    "_matter._tcp.",
    "_matterc._udp.",
    "_airprint._tcp.",
    "_vnc._tcp."
]

public let commonKnownServiceTypes: [String: String] = [
    "_airplay._tcp.":       NSLocalizedString("Protocol for streaming of audio/video content", comment: ""),
    "_raop._tcp.":          NSLocalizedString("Remote Audio Output Protocol (AirTunes)", comment: ""),
    "_sftp-ssh._tcp.":      NSLocalizedString("Secure File Transfer Protocol over SSH", comment: ""),
    "_sleep-proxy._udp.":   NSLocalizedString("Sleep Proxy Server", comment: ""),
    "_ssh._tcp.":           NSLocalizedString("SSH Remote Login Protocol", comment: ""),
    "_http._tcp.":          NSLocalizedString("World Wide Web (HTTP)", comment: ""),
    "_https._tcp.":         NSLocalizedString("World Wide Web (HTTPS)", comment: ""),
    "_smb._tcp.":           NSLocalizedString("SMB File Sharing", comment: ""),
    "_afpovertcp._tcp.":    NSLocalizedString("Apple Filing Protocol (AFP)", comment: ""),
    "_printer._tcp.":       NSLocalizedString("Printer", comment: ""),
    "_ipp._tcp.":           NSLocalizedString("Internet Printing Protocol", comment: ""),
    "_scanner._tcp.":       NSLocalizedString("Scanner", comment: ""),
    "_ftp._tcp.":           NSLocalizedString("File Transfer Protocol", comment: ""),
    "_nfs._tcp.":           NSLocalizedString("Network File System", comment: ""),
    "_daap._tcp.":          NSLocalizedString("Digital Audio Access Protocol (iTunes)", comment: ""),
    "_dpap._tcp.":          NSLocalizedString("Digital Photo Access Protocol (iPhoto)", comment: ""),
    "_airport._tcp.":       NSLocalizedString("AirPort Base Station", comment: ""),
    "_homekit._tcp.":       NSLocalizedString("HomeKit Accessory", comment: ""),
    "_hap._tcp.":           NSLocalizedString("HomeKit Accessory Protocol", comment: ""),
    "_companion-link._tcp.": NSLocalizedString("Companion Link (Apple Watch)", comment: ""),
    "_apple-mobdev2._tcp.":  NSLocalizedString("Apple Mobile Device v2", comment: ""),
    "_remotepairing._tcp.":  NSLocalizedString("Remote Pairing", comment: ""),
    "_remotepairing-pairable-host._tcp.": NSLocalizedString("Remote Pairing (Pairable Host)", comment: ""),
    "_remotepairing-manual-pairing._tcp.": NSLocalizedString("Remote Pairing (Manual / Apple TV)", comment: ""),
    "_rdlink._tcp.":        NSLocalizedString("Remote Debug Link", comment: ""),
    "_net-assistant._udp.": NSLocalizedString("Apple Remote Desktop", comment: ""),
    "_rfb._tcp.":           NSLocalizedString("Remote Frame Buffer (VNC)", comment: ""),
    "_spotify-connect._tcp.": NSLocalizedString("Spotify Connect", comment: ""),
    "_googlecast._tcp.":    NSLocalizedString("Google Cast (Chromecast)", comment: ""),
    "_meshcop._udp.":       NSLocalizedString("Thread Mesh Commissioning", comment: ""),
    "_asquic._udp.":        NSLocalizedString("Apple QUIC Service", comment: ""),
    "_rp-tunnel._tcp.":     NSLocalizedString("Remote Pairing Tunnel", comment: ""),
    "_altserver._tcp.":     NSLocalizedString("AltServer", comment: ""),
    "_workstation._tcp.":   NSLocalizedString("Workstation", comment: ""),
    "_device-info._tcp.":   NSLocalizedString("Device Info", comment: ""),
    "_touch-able._tcp.":    NSLocalizedString("Remote App (Apple TV Remote)", comment: ""),
    "_srpl-tls._tcp.":      NSLocalizedString("Spatial Remote Playback Link TLS", comment: ""),
    "_trel._udp.":          NSLocalizedString("Thread Radio Encapsulation Link", comment: ""),
    "_ipps._tcp.":          NSLocalizedString("Secure Internet Printing Protocol", comment: ""),
    "_webdav._tcp.":        NSLocalizedString("Web Distributed Authoring and Versioning (WebDAV)", comment: ""),
    "_webdavs._tcp.":       NSLocalizedString("Secure WebDAV", comment: ""),
    "_telnet._tcp.":        NSLocalizedString("Telnet Remote Login Protocol", comment: ""),
    "_coap._udp.":          NSLocalizedString("Constrained Application Protocol (CoAP)", comment: ""),
    "_coaps._udp.":         NSLocalizedString("Secure CoAP", comment: ""),
    "_mqtt._tcp.":          NSLocalizedString("Message Queuing Telemetry Transport (MQTT)", comment: ""),
    "_adb._tcp.":           NSLocalizedString("Android Debug Bridge (ADB)", comment: ""),
    "_airdrop._tcp.":       NSLocalizedString("Apple AirDrop", comment: ""),
    "_sidecar._tcp.":       NSLocalizedString("Apple Sidecar", comment: ""),
    "_sonos._tcp.":         NSLocalizedString("Sonos Speaker System", comment: ""),
    "_plex._tcp.":          NSLocalizedString("Plex Media Server", comment: ""),
    "_amzn-alexa._tcp.":    NSLocalizedString("Amazon Alexa Service", comment: ""),
    "_home-assistant._tcp.": NSLocalizedString("Home Assistant Smart Home", comment: ""),
    "_rtsp._tcp.":          NSLocalizedString("Real Time Streaming Protocol (RTSP)", comment: ""),
    "_sip._udp.":           NSLocalizedString("Session Initiation Protocol (SIP over UDP)", comment: ""),
    "_sip._tcp.":           NSLocalizedString("Session Initiation Protocol (SIP over TCP)", comment: ""),
    "_h323._tcp.":          NSLocalizedString("H.323 Video Conferencing (TCP)", comment: ""),
    "_h323._udp.":          NSLocalizedString("H.323 Video Conferencing (UDP)", comment: ""),
    "_ws._tcp.":            NSLocalizedString("WebSocket Connection", comment: ""),
    "_wss._tcp.":           NSLocalizedString("Secure WebSocket Connection", comment: ""),
    "_remoted._tcp.":       NSLocalizedString("CoreDevice Remote Service Discovery (RSD)", comment: ""),
    "_coredevice._tcp.":    NSLocalizedString("Apple CoreDevice Debug Service", comment: ""),
    "_appletv-v2._tcp.":    NSLocalizedString("Apple TV Companion Remote Protocol", comment: ""),
    "_apple-mobdev._tcp.":  NSLocalizedString("Apple Mobile Device v1 (Wi-Fi Sync)", comment: ""),
    "_jitstreamer._tcp.":   NSLocalizedString("JitStreamer Service", comment: ""),
    "_matter._tcp.":        NSLocalizedString("Matter Smart Home Device", comment: ""),
    "_matterc._udp.":       NSLocalizedString("Matter Device Commissioning", comment: ""),
    "_airprint._tcp.":      NSLocalizedString("Apple AirPrint", comment: ""),
    "_vnc._tcp.":           NSLocalizedString("VNC Remote Desktop", comment: ""),
]

public extension String {
    // Strips the network interface scope suffix (e.g. "%en0", "%pdp_ip0") from an IP address or hostname.
    var strippingInterfaceScope: String {
        if let percentIndex = self.firstIndex(of: "%") {
            return String(self[..<percentIndex])
        }
        return self
    }
}

