name: SideStore Shared

on:
  workflow_call:
    outputs:
      short-commit: 
        value: ${{ jobs.shared.outputs.short-commit }}

jobs:
  shared:
    name: Shared Steps
    strategy:
      fail-fast: false
    runs-on: 'macos-15'
    steps:
      - name: Set short commit hash
        id: commit-id
        run: |
          # SHORT_COMMIT="${{ github.sha }}"
          SHORT_COMMIT=${GITHUB_SHA:0:7}
          echo "Short commit hash: $SHORT_COMMIT"
          echo "SHORT_COMMIT=$SHORT_COMMIT" >> $GITHUB_OUTPUT
    outputs:
      short-commit: ${{ steps.commit-id.outputs.SHORT_COMMIT }}